import { BadgeCheck, Building2, CalendarClock, Languages, MapPin, Phone, Plus, Search, Star, UsersRound } from 'lucide-react';
import { type ReactElement, type ReactNode, useMemo, useState } from 'react';

const agencies = [
  { id:'travelmate', name:'트래블메이트', manager:'김민지', phone:'02-6204-1187', requests:8, active:2, last:'오늘', grade:'핵심 파트너', note:'기업 인센티브 및 VIP 투어 중심' },
  { id:'hanaro', name:'하나로투어', manager:'박서준', phone:'02-771-4201', requests:12, active:1, last:'어제', grade:'일반', note:'일본 기업 및 산업 시찰 요청 다수' },
  { id:'k-convention', name:'K-컨벤션', manager:'이수현', phone:'051-903-7740', requests:5, active:3, last:'08.08', grade:'핵심 파트너', note:'부산 지역 국제 컨벤션 전문' },
  { id:'modu', name:'모두여행', manager:'최유진', phone:'02-3401-9912', requests:17, active:2, last:'08.07', grade:'핵심 파트너', note:'동남아 단체 및 인센티브 투어' },
  { id:'bridge', name:'브릿지트래블', manager:'정우석', phone:'02-557-2103', requests:4, active:1, last:'08.06', grade:'일반', note:'교육 및 대학 교류 프로그램' },
];
const guides = [
  { name:'김하늘', languages:['영어','스페인어'], region:'서울 · 경기', career:'8년', rating:4.9, matches:32, status:'매칭 가능', tags:['관광통역안내사','VIP 수행'] },
  { name:'사토 유키', languages:['일본어','한국어'], region:'서울 · 인천', career:'6년', rating:4.8, matches:27, status:'일정 확인', tags:['산업 시찰','비즈니스'] },
  { name:'왕리', languages:['중국어','영어'], region:'부산 · 경남', career:'5년', rating:4.9, matches:19, status:'매칭 가능', tags:['MICE','차량 운전'] },
  { name:'응우옌 민', languages:['베트남어','한국어'], region:'제주', career:'4년', rating:4.7, matches:15, status:'진행 중', tags:['단체 인솔','인센티브'] },
  { name:'Emma Lee', languages:['영어','프랑스어'], region:'전국', career:'9년', rating:5.0, matches:41, status:'매칭 가능', tags:['VIP 수행','국제회의'] },
  { name:'박지훈', languages:['영어','일본어'], region:'대전 · 충청', career:'7년', rating:4.8, matches:24, status:'일정 확인', tags:['교육 연수','문화 관광'] },
];

export function AdminPartnersPage({ mode }: { mode:'agencies'|'guides' }) { return mode==='agencies'?<Agencies/>:<Guides/> }

function Agencies(){ const [query,setQuery]=useState(''); const [selected,setSelected]=useState(agencies[0]!); const filtered=agencies.filter(a=>a.name.includes(query)||a.manager.includes(query)); return <main className="mx-auto max-w-[1500px] p-4 sm:p-7 lg:p-8"><PageHead eyebrow="AGENCIES" title="여행사 관리" description="파트너 여행사 정보와 누적 요청 이력을 관리하세요." button="여행사 등록" icon={<Building2 className="size-4"/>}/><div className="mt-7 grid gap-5 xl:grid-cols-[1.5fr_.75fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><SearchBox value={query} onChange={setQuery} placeholder="여행사명 또는 담당자 검색"/></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">여행사</th><th>누적 요청</th><th>진행 중</th><th>최근 요청</th><th>등급</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(a=><tr key={a.name} onClick={()=>setSelected(a)} className={`cursor-pointer hover:bg-slate-50 ${selected.name===a.name?'bg-rose-50/40':''}`}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-xl bg-slate-100 font-bold text-slate-500">{a.name[0]}</span><div><b>{a.name}</b><p className="mt-1 text-xs text-slate-400">{a.manager} 담당자</p></div></div></td><td className="font-semibold">{a.requests}건</td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-blue-600">{a.active}건</span></td><td className="text-slate-500">{a.last}</td><td><span className={a.grade==='핵심 파트너'?'text-rose-500 font-semibold':'text-slate-400'}>{a.grade}</span></td></tr>)}</tbody></table></div></section><AgencyDetail agency={selected}/></div></main> }

function AgencyDetail({agency}:{agency:typeof agencies[number]}){return <aside className="rounded-2xl border border-slate-200 bg-white p-6"><div className="flex size-12 items-center justify-center rounded-2xl bg-rose-50 text-xl font-bold text-rose-500">{agency.name[0]}</div><h2 className="mt-4 text-xl font-bold">{agency.name}</h2><p className="mt-1 text-xs font-semibold text-rose-500">{agency.grade}</p><div className="mt-6 space-y-4 text-sm"><InfoRow icon={<UsersRound/>} label="담당자" value={agency.manager}/><InfoRow icon={<Phone/>} label="연락처" value={agency.phone}/><InfoRow icon={<CalendarClock/>} label="누적 요청" value={`${agency.requests}건`}/></div><div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-400">내부 메모</p><p className="mt-2 text-sm leading-6 text-slate-600">{agency.note}</p></div><a className="mt-6 flex w-full items-center justify-center rounded-xl bg-slate-900 py-3 text-sm font-semibold text-white transition hover:bg-slate-800" href={`/admin/agencies/${agency.id}`}>여행사 상세 보기</a></aside>}

function Guides(){const [query,setQuery]=useState('');const filtered=useMemo(()=>guides.filter(g=>`${g.name} ${g.languages.join(' ')} ${g.region}`.toLowerCase().includes(query.toLowerCase())),[query]);return <main className="mx-auto max-w-[1500px] p-4 sm:p-7 lg:p-8"><PageHead eyebrow="GUIDES" title="가이드 관리" description="언어, 지역, 경력에 맞는 가이드를 검색하고 일정을 확인하세요." button="가이드 등록" icon={<UsersRound className="size-4"/>}/><div className="mt-7 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row"><SearchBox value={query} onChange={setQuery} placeholder="이름, 언어, 활동 지역 검색"/><select className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option>전체 활동 지역</option><option>서울 · 경기</option><option>부산 · 경남</option><option>제주</option></select><select className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option>전체 상태</option><option>매칭 가능</option><option>일정 확인</option></select></div><section className="mt-5 grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{filtered.map(g=><article className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-lg" key={g.name}><div className="flex items-start"><span className="flex size-12 items-center justify-center rounded-full bg-slate-900 font-bold text-white">{g.name.slice(0,1)}</span><div className="ml-3"><div className="flex items-center gap-1.5"><h2 className="font-bold">{g.name}</h2><BadgeCheck className="size-4 text-blue-500"/></div><p className="mt-1 flex items-center gap-1 text-xs text-amber-500"><Star className="size-3 fill-current"/>{g.rating} <span className="text-slate-400">· 매칭 {g.matches}회</span></p></div><span className={`ml-auto rounded-full px-2.5 py-1 text-[11px] font-bold ${g.status==='매칭 가능'?'bg-emerald-50 text-emerald-600':g.status==='진행 중'?'bg-blue-50 text-blue-600':'bg-amber-50 text-amber-600'}`}>{g.status}</span></div><div className="mt-5 space-y-2 text-xs text-slate-500"><p className="flex items-center gap-2"><Languages className="size-4 text-slate-400"/>{g.languages.join(' · ')}</p><p className="flex items-center gap-2"><MapPin className="size-4 text-slate-400"/>{g.region} · 경력 {g.career}</p></div><div className="mt-4 flex flex-wrap gap-1.5">{g.tags.map(t=><span className="rounded-md bg-slate-100 px-2 py-1 text-[11px] text-slate-500" key={t}>{t}</span>)}</div><button className="mt-5 w-full rounded-xl border border-slate-200 py-2.5 text-sm font-semibold hover:border-rose-200 hover:text-rose-500">프로필 및 일정 보기</button></article>)}</section></main>}

function PageHead({eyebrow,title,description,button,icon}:{eyebrow:string;title:string;description:string;button:string;icon:ReactNode}){return <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-rose-500">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div><button className="flex h-10 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-semibold text-white"><Plus className="size-4"/>{button}{icon}</button></div>}
function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="flex h-10 min-w-64 flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3"><Search className="size-4 text-slate-400"/><input className="w-full bg-transparent text-sm outline-none" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function InfoRow({icon,label,value}:{icon:ReactElement;label:string;value:string}){return <div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-slate-50 text-slate-400">{icon}</span><div><p className="text-[11px] text-slate-400">{label}</p><p className="font-medium">{value}</p></div></div>}
